# Base Image
ARG BASE_IMAGE=pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get install -yq -qq \
    git \
    vim \
    curl \
    # pyenv dependencies
    build-essential \ 
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev \
    locales \
    && rm -rf /var/lib/apt/lists/*

# locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# pyenv install
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv 
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/bin:$PATH

# poetry install
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

# bash alias
# RUN echo 'alias hg="history | grep"' >> ~/.bashrc \
#    && echo 'alias pr="poetry run"' >> ~/.bashrc

# bash theme
RUN git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it \
    && ~/.bash_it/install.sh --silent \
    && echo 'export BASH_IT_THEME="bakke"' >> ~/.bashrc

